[project]
name = "gateway"
version = "0.1.0"
description = "Single entry point that proxies frontend traffic to backend/retriever/agent/cv_service"
authors = [
    {name = "Ivan Shebanov", email = "vanamokanov8@gmail.com"},
]
dependencies = [
    "fastapi>=0.121.0",
    "uvicorn[standard]>=0.40.0",
    "httpx>=0.28.1",
    "websockets>=13.0",
]
requires-python = "==3.12.*"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
start.cmd = "python ./src/main.py"
start.env = {PYTHONPATH = "./src"}
