FROM python:3.12-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg libgl1 libglib2.0-0 libgles2 libegl1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install pdm

COPY pyproject.toml ./
RUN pdm install --prod --no-editable --no-lock

COPY ./src ./src
COPY ./pose_landmarker_full.task ./pose_landmarker_full.task
