"""{initial migration}

Revision ID: 260769184a15
Revises: 2e22b1ce7167
Create Date: 2025-12-22 05:15:42.214275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260769184a15'
down_revision: Union[str, Sequence[str], None] = '2e22b1ce7167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('repetitions', sa.Integer(), nullable=True))
    op.drop_column('sets', 'repetions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('repetions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sets', 'repetitions')
    # ### end Alembic commands ###
