"""{initial migration}

Revision ID: 2e22b1ce7167
Revises: 03a65471383d
Create Date: 2025-12-22 03:24:35.112547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e22b1ce7167'
down_revision: Union[str, Sequence[str], None] = '03a65471383d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'exercises', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='unique')
    # ### end Alembic commands ###
